server:
  port: 8087

interpretador:
  itsm:
    url: ${ITSM_INTERPRETADOR_URL}
    query: ${ITSM_QUERY}

relatorio.cron: ${CRONTAB:* * * * * *}

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration